[build]
publish = "/public"
command = "hugo -d public && pagedjs-cli public/index.html -o public/index.pdf"

[context.production.environment]
  HUGO_VERSION = "0.70.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.70.0"
  
[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL"